# == Schema Information
#
# Table name: recruiters
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RecruitersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Recruiter. As you add validations to Recruiter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecruitersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all recruiters as @recruiters" do
      recruiter = Recruiter.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:recruiters)).to eq([recruiter])
    end
  end

  describe "GET #show" do
    it "assigns the requested recruiter as @recruiter" do
      recruiter = Recruiter.create! valid_attributes
      get :show, {:id => recruiter.to_param}, valid_session
      expect(assigns(:recruiter)).to eq(recruiter)
    end
  end

  describe "GET #new" do
    it "assigns a new recruiter as @recruiter" do
      get :new, {}, valid_session
      expect(assigns(:recruiter)).to be_a_new(Recruiter)
    end
  end

  describe "GET #edit" do
    it "assigns the requested recruiter as @recruiter" do
      recruiter = Recruiter.create! valid_attributes
      get :edit, {:id => recruiter.to_param}, valid_session
      expect(assigns(:recruiter)).to eq(recruiter)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Recruiter" do
        expect {
          post :create, {:recruiter => valid_attributes}, valid_session
        }.to change(Recruiter, :count).by(1)
      end

      it "assigns a newly created recruiter as @recruiter" do
        post :create, {:recruiter => valid_attributes}, valid_session
        expect(assigns(:recruiter)).to be_a(Recruiter)
        expect(assigns(:recruiter)).to be_persisted
      end

      it "redirects to the created recruiter" do
        post :create, {:recruiter => valid_attributes}, valid_session
        expect(response).to redirect_to(Recruiter.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved recruiter as @recruiter" do
        post :create, {:recruiter => invalid_attributes}, valid_session
        expect(assigns(:recruiter)).to be_a_new(Recruiter)
      end

      it "re-renders the 'new' template" do
        post :create, {:recruiter => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested recruiter" do
        recruiter = Recruiter.create! valid_attributes
        put :update, {:id => recruiter.to_param, :recruiter => new_attributes}, valid_session
        recruiter.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested recruiter as @recruiter" do
        recruiter = Recruiter.create! valid_attributes
        put :update, {:id => recruiter.to_param, :recruiter => valid_attributes}, valid_session
        expect(assigns(:recruiter)).to eq(recruiter)
      end

      it "redirects to the recruiter" do
        recruiter = Recruiter.create! valid_attributes
        put :update, {:id => recruiter.to_param, :recruiter => valid_attributes}, valid_session
        expect(response).to redirect_to(recruiter)
      end
    end

    context "with invalid params" do
      it "assigns the recruiter as @recruiter" do
        recruiter = Recruiter.create! valid_attributes
        put :update, {:id => recruiter.to_param, :recruiter => invalid_attributes}, valid_session
        expect(assigns(:recruiter)).to eq(recruiter)
      end

      it "re-renders the 'edit' template" do
        recruiter = Recruiter.create! valid_attributes
        put :update, {:id => recruiter.to_param, :recruiter => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested recruiter" do
      recruiter = Recruiter.create! valid_attributes
      expect {
        delete :destroy, {:id => recruiter.to_param}, valid_session
      }.to change(Recruiter, :count).by(-1)
    end

    it "redirects to the recruiters list" do
      recruiter = Recruiter.create! valid_attributes
      delete :destroy, {:id => recruiter.to_param}, valid_session
      expect(response).to redirect_to(recruiters_url)
    end
  end

end
